development:
  adapter: postgresql
  encoding: unicode
  database: bpsearcher_development
  pool: 5
  username: bpsearcher
  password: bpsearcher

test: &test
  adapter: postgresql
  encoding: unicode
  database: bpsearcher_test
  pool: 5
  username: bpsearcher
  password: bpsearcher

staging:
  adapter: postgresql
  encoding: unicode
  database: bpsearcher_staging
  pool: 5
  username: bpsearcher
  password: bpsearcher

production:
  adapter: postgresql
  encoding: unicode
  database: bpsearcher_production
  pool: 5
  username: bpsearcher
  password: bpsearcher

cucumber:
  <<: *test
